### ISSUE TITLE
Road in Lward and S ward not seen

### ISSUE THREAD

**Issue by MonikaShah** [AnimeshN/community-gis#3]
WE now have on google my map many roads of 122 corporator ward and L ( admin) ward
Can @asma ensure the same to be displayed in communiytygis .
![Screenshot from 2019-11-24 16-24-24](https://user-images.githubusercontent.com/4188149/69493635-ec642e00-0ed6-11ea-927d-f83bc16aea5c.png)

**Comment by jitendrashahiitb** [comment]
This was actually my issue. But i did not notice Monika had been logged in.

**Comment by AnimeshN** [comment]
I will assign asmabee to see this

**Comment by asmabee07** [comment]
ok

**Comment by AnimeshN** [comment]
@asmabee07 is it resolved?
